AppleSignInProperties structure and all related members
heremaps/here-data-sdk-cpp pull request #1165
Opened 2021-02-26 09:04 UTC by andrey-kashcheev

First step on Apple Sign-In support

Relates-To: OLPEDGE-2482
Signed-off-by: Andrey Kashcheev <ext-andrey.kashcheev@here.com>

2021-02-26 10:40 UTC, andescu reviewed
Please enhance the commit message. Describe what you are adding and what it will be used for and why do we add it.

2021-02-26 10:40 UTC, andescu commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +  struct AppleSignInProperties {
Let's change this awful approach and not do a nested struct. Please move to a separate file.

2021-02-26 12:29 UTC, HalynaDumych requested changes

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +   * @brief The Apple sign-in properties structure.
```suggestion
   * @brief The structure of the Apple sign-in properties.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * request header.
```suggestion
     * @brief The Apple ID token to be used as a bearer in the authorization
     * request header.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * @brief OIDC name property for the user.
Can we put it in the following way?
```suggestion
     * @brief Your OIDC name.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * sign-ins.
```suggestion
     * Required for the first-time sign-in; optional for the subsequent
     * sign-ins.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * sign-ins.
```suggestion
     * Required for the first-time sign-in; optional for the subsequent
     * sign-ins.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * sign-ins.
```suggestion
     * Required for the first-time sign-in; optional for the subsequent
     * sign-ins.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * @brief The application id.
```suggestion
     * @brief The application ID.
```

2021-02-26 12:29 UTC, HalynaDumych commented on olp-cpp-sdk-authentication/include/olp/authentication/AuthenticationClient.h
> +     * to.
```suggestion
     * @brief The platform realm to which the application ID (`client_id`) belongs.
```

2021-03-01 10:04 UTC, HalynaDumych submitted a review, later dismissed

2021-03-01 10:20 UTC, andescu commented on olp-cpp-sdk-authentication/include/olp/authentication/AppleSignInProperties.h
> +#include "AuthenticationApi.h"
Please include it with global includes, means <olp/authentication/AuthenticationApi.h>

2021-03-01 10:20 UTC, andescu commented on olp-cpp-sdk-authentication/include/olp/authentication/AppleSignInProperties.h
> +   * @note The 'id_token' received after authorization should be used here.
Is this correct? No mention that this is an Apple id_token taken from Apple authentication. Please adapt this and the above GetAccessToken() Doxygen to mention that we are talking about a Apple token here.

2021-03-01 11:10 UTC, andescu approved these changes

2021-03-01 11:14 UTC, kzvieriev approved these changes

2021-03-01 11:28 UTC, merged