Add classes for comptabile versions request.
heremaps/here-data-sdk-cpp pull request #1299
Opened 2022-01-11 11:54 UTC by meravingen123

Resolves: OAM-1338

Signed-off-by: Serhii Lozynskyi <ext-serhii.lozynskyi@here.com>

2022-01-11 12:34 UTC, HalynaDumych requested changes

2022-01-11 12:34 UTC, HalynaDumych commented on olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Dependencies.h
> +/// Represents a dependencies for a given catalog version.
```suggestion
/// Represents dependencies for the given catalog version.
```

2022-01-11 12:34 UTC, HalynaDumych commented on olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/Dependencies.h
> +   * @param version_infos The information of the dependencies.
```suggestion
   * @brief Sets the information on the dependencies.
   *
   * @param version_infos The information on the dependencies.
```

2022-01-11 16:37 UTC, andescu commented on olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/CatalogVersion.h
> +  int64_t version_;
It would make sense to add default values here, else this will generate some nice compiler warnings. 
```suggestion
  int64_t version_{0};
```

2022-01-11 16:37 UTC, andescu commented on olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/model/CatalogVersion.h
> +#include <utility>
Order of includes is not correct.

2022-01-12 11:06 UTC, HalynaDumych approved these changes

2022-01-12 12:27 UTC, andescu approved these changes

2022-01-12 15:57 UTC, merged