Censor credentials in debug log messages.
heremaps/here-data-sdk-cpp pull request #1434
Opened 2023-09-27 12:36 UTC by Smartkras

Censoring of credentials was added to debug log messages for Windows, Android and curl implementation.

Resolves: OAM-2216

2023-09-28 08:08 UTC, andrey-kashcheev commented on olp-cpp-sdk-core/include/olp/core/utils/Credentials.h
> + * Copyright (C) 2019-2023 HERE Europe B.V.
Here and in the cpp 2023 only, as this is a new file technically

2023-09-28 08:08 UTC, andrey-kashcheev commented on olp-cpp-sdk-core/tests/utils/UtilsTest.cpp
> +TEST(UtilsTest, Credentials) {
Maybe split with SCOPED_TRACE? 
- Empty url
- Nothing to censor
- Censoring app_id, app_code

2023-09-28 08:11 UTC, mykhailo-kuchma requested changes

2023-09-28 08:11 UTC, mykhailo-kuchma commented on olp-cpp-sdk-core/src/utils/Credentials.cpp
> +void censor_credentials_part(std::string& url, std::size_t arguments_start,
CensorCredentialsPart

2023-09-28 08:11 UTC, mykhailo-kuchma commented on olp-cpp-sdk-core/src/utils/Credentials.cpp
> +  censor_credentials_part(url, arguments_start_pos, app_code_name);
Can you also try the API key authentication and censor it

2023-09-28 18:01 UTC, andrey-kashcheev approved these changes

2023-09-29 08:13 UTC, mykhailo-kuchma approved these changes

2023-09-29 08:36 UTC, merged