Release v1.18.0
heremaps/here-data-sdk-cpp pull request #1483
Opened 2024-03-04 10:37 UTC by andrey-kashcheev

Updated changelog, CMake versions, readme

Relates-To: OLPEDGE-2868

2024-03-05 10:23 UTC, tomekpapiernik requested changes

2024-03-05 10:23 UTC, tomekpapiernik commented on CHANGELOG.md
> +* Now, the credentials file is being correctly parsed when has unexpected line endings (e.g. when file had been copied from one system to another one).
```suggestion
* The credentials file is parsed correctly when it has unexpected line endings which can occur when copying the file between different operating systems.
```

2024-03-05 10:23 UTC, tomekpapiernik commented on CHANGELOG.md
> +* Fixed possible crash in `olp::dataservice::read::PartitionsCacheRepository` when the stream was closed before parsing had been started.
```suggestion
* Fixed possible crash in `olp::dataservice::read::PartitionsCacheRepository` that occurred when the stream closed before parsing started.
```

2024-03-05 10:23 UTC, tomekpapiernik commented on CHANGELOG.md
> +* Added additional checks for the result of cache related operations.
```suggestion
* Added more checks for the results of cache-related operations.
```

2024-03-05 10:23 UTC, tomekpapiernik commented on CHANGELOG.md
> +* Changed the `olp::dataservice::read::VersionedLayerClient::Release` to take into account the list of tiles from the request and assume that they will be released.
```suggestion
* Updated `olp::dataservice::read::VersionedLayerClient::Release` to take the list of tiles from the request take into account and assume that they will be released.
```

2024-03-05 10:23 UTC, tomekpapiernik commented on CHANGELOG.md
> +* Added performance improvements.
```suggestion
* Introduced performance improvements.
```

2024-03-06 09:49 UTC, tomekpapiernik approved these changes

2024-03-06 11:21 UTC, rustam-gamidov-here approved these changes

2024-03-06 13:27 UTC, mykolamalik approved these changes

2024-03-06 14:32 UTC, merged