IOTSDK-24021: Fix parsing of server DateTime
heremaps/here-data-sdk-cpp pull request #1499
Opened 2024-04-19 15:31 UTC by diachenko-mischa

std::get_time does not claim support of time zones in the string parameter, and seems to be subject of locale set on the system. An example is a following result on linux:

ParseTime(Thu, 1 Jan 1970 0:00:00 GMT)=-2209075200

::strptime is also a subject to the time zones of locale, but it also claim support for parsing a time zone from the passed string. Thus, additional logic incorporated to offset parsed DataTime to the local timezone.

2024-04-22 10:56 UTC, mykolamalik requested changes
Please update the names of functions and variables in order to follow the project's code style: UpperCamelCase for function names, snake_case for variables

2024-04-22 17:02 UTC, diachenko-mischa commented
> Please update the names of functions and variables in order to follow the project's code style: UpperCamelCase for function names, snake_case for variables

Fixed

2024-04-22 17:21 UTC, mykolamalik approved these changes

2024-04-23 10:36 UTC, mykhailo-kuchma approved these changes

2024-04-23 11:43 UTC, merged